version: '{build}'
image: Visual Studio 2022
platform:
  - x64

environment:
  nodejs_version: 16
  appveyor_repo_tag: false  # Disable tagging for builds unless needed

cache:
  - node_modules
  - .webpack/  # Cache the Electron build outputs

init:
  # Ensure Node.js is available
  - ps: Install-Product node $env:nodejs_version

install:
  # Install dependencies
  - npm install
  - npm install --save-dev electron-builder
  - npm run postinstall  # Rebuild native modules (serialport, etc.)

build_script:
  # Build the production version of your Electron app
  - npm run package

test_script:
  # Run tests (optional, ERB comes with test configuration)
  - npm test

artifacts:
  # Save the packaged application
  - path: dist\*
    name: ElectronReactBoilerplate

deploy:
  # Example deployment step (optional, only for tagged commits)
  on:
    branch: main
    appveyor_repo_tag: true
