name: Build Electron App

on:
  push:
    branches:
      - main  # Run the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Run on pull requests to the main branch

jobs:
  build:
    runs-on: windows-latest  # Use Windows for building

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          npm install
          npm run postinstall  # Rebuild native modules if needed

      - name: Build Application
        run: |
          npm run package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ElectronApp
          path: release/build/
